from posixpath import basename
from django.urls import path
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register('roles',views.RoleViewSet)
router.register('taluks',views.TalukViewSet)
router.register('blocks',views.BlockViewSet)
router.register('panchayats',views.PanchayatViewSet)
router.register('waterbodytypes',views.WaterBodyTypeViewSet)
router.register('waterbodyownerships',views.WaterBodyOwnerShipViewSet)
router.register('months',views.MonthViewSet)
router.register('waterbodysources',views.WaterBodySourceViewSet)
router.register('waterbodycrosssections',views.WaterBodyCrossSectionViewSet)
router.register('waterbodystreamissues',views.WaterBodyStreamIssuesViewSet)
router.register('waterbodyexoticspecies',views.WaterBodyExoticSpeciesViewSet)
router.register('waterbodybunds',views.WaterBodyBundViewSet)
router.register('waterbodytankissues',views.WaterBodyTankIssuesViewSet)
router.register('waterbodystonepitchings',views.WaterBodyStonePitchingViewSet)
router.register('waterbodystonepitchingconditions',views.WaterBodyStonePitchingConditionViewSet)
router.register('waterbodysluices',views.WaterBodySluiceViewSet)
router.register('waterbodydepthsilllevels',views.WaterBodyDepthSillLevelViewSet)
router.register('waterbodyshutters',views.WaterBodyShutterViewSet)
router.register('waterbodyconditions',views.WaterBodyConditionViewSet)
router.register('waterbodyshutterconditions',views.WaterBodyShutterConditionViewSet)
router.register('waterbodysurplusweirs',views.WaterBodySurplusWeirViewSet)
router.register('waterbodymwlstones',views.WaterBodyMWLStoneViewSet)
router.register('waterbodyirrigationtankfunctions',views.WaterBodyIrrigationTankFunctionViewSet)
router.register('waterbodyayacutnoncultivations',views.WaterBodyAyacutNonCultivationViewSet)
router.register('waterbodycroppings',views.WaterBodyCroppingViewSet)
router.register('waterbodynatureinvestments',views.WaterBodyInvestmentNatureViewSet)
router.register('waterbodyfamilynatures',views.WaterBodyFamilyNatureViewSet)
router.register('waterbodyfamilydistributionlands',views.WaterBodyFamilyDistributionLandViewSet)
router.register('waterbodytankuniqueness',views.WaterBodyTankUniquenessViewSet)
router.register('waterbodyboundarydroppoints',views.WaterBodyBoundaryDropPointViewSet)
router.register('waterbodytypes',views.WaterBodyTypeViewSet)
router.register('waterbodytempletanktypes',views.WaterBodyTempleTankTypeViewSet)
router.register('waterbodyinlettypes',views.WaterBodyInletTypeViewSet)
router.register('waterbodyslittraps',views.WaterBodySlitTrapViewSet)
router.register('waterbodyoutlettypes',views.WaterBodyOutletTypeViewSet)
router.register('waterbodyghatconditions',views.WaterBodyGhatConditionViewSet)
router.register('waterbodyfenceconditions',views.WaterBodyFenceConditionViewSet)
router.register('waterbodyfencetypes',views.WaterBodyFenceTypeViewSet)
router.register('waterbodyooranifunctions',views.WaterBodyOoraniFunctionViewSet)
router.register('userprofile',views.UserProfileViewSet)
router.register('allusers',views.UserList,basename='allusers')
router.register('tankImage',views.TankImageViewSet)
router.register('tankMetaData',views.TankMetaDataViewSet)
router.register('surveyQuestion',views.SurevyQuestionViewSet)

#URL Config Module
urlpatterns = router.urls
