# Generated by Django 4.0.3 on 2022-03-19 15:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestionMetaData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TankMetaData',
            fields=[
                ('Unique_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('FID', models.CharField(max_length=255)),
                ('CLUSTER', models.CharField(max_length=255)),
                ('TANK_NUM', models.CharField(max_length=255)),
                ('Tank_Name', models.CharField(max_length=255)),
                ('Latitude', models.CharField(max_length=255)),
                ('Longitude', models.CharField(max_length=255)),
                ('Village', models.CharField(max_length=255)),
                ('Block', models.CharField(max_length=255)),
                ('Taluk', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
                ('Subbasin', models.CharField(max_length=255)),
                ('Basin', models.CharField(max_length=255)),
                ('Section', models.CharField(max_length=255)),
                ('Sub_Dn', models.CharField(max_length=255)),
                ('Division', models.CharField(max_length=255)),
                ('Circle', models.CharField(max_length=255)),
                ('Region', models.CharField(max_length=255)),
                ('Tank_Type', models.CharField(max_length=255)),
                ('Cap_MCM', models.CharField(max_length=255)),
                ('FTL_m', models.CharField(max_length=255)),
                ('MWL_m', models.CharField(max_length=255)),
                ('TBL_m', models.CharField(max_length=255)),
                ('Sto_Dep_m', models.CharField(max_length=255)),
                ('Ayacut_ha', models.CharField(max_length=255)),
                ('Catch_sqkm', models.CharField(max_length=255)),
                ('Wat_Spr_ha', models.CharField(max_length=255)),
                ('No_of_Weir', models.CharField(max_length=255)),
                ('Weir_Len_m', models.CharField(max_length=255)),
                ('No_Sluice', models.CharField(max_length=255)),
                ('Low_Sil_m', models.CharField(max_length=255)),
                ('Bund_Len_m', models.CharField(max_length=255)),
                ('Dis_cusec', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('middleName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.role')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.user')),
            ],
        ),
        migrations.CreateModel(
            name='TankSurveyQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('responseText', models.TextField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.surveyquestionmetadata')),
            ],
        ),
    ]
