# Generated by Django 4.0.4 on 2022-07-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankimage',
            name='filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
