# Generated by Django 4.0.3 on 2022-03-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.role'),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
