# Generated by Django 4.0.4 on 2022-07-07 12:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0002_permissiontype_resource_resourcepermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissionaccessright', to='waterBodyAdmin.permissiontype')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourceacessright', to='waterBodyAdmin.resource')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleaccessright', to='waterBodyAdmin.role')),
            ],
        ),
        migrations.CreateModel(
            name='ResourcePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.permissiontype')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.resource')),
            ],
        ),
        migrations.DeleteModel(
            name='ResourcePermissions',
        ),
    ]
