# Generated by Django 4.0.3 on 2022-03-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0002_user_role_delete_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='lastModifiedBy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
