# Generated by Django 4.0.4 on 2022-07-08 01:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0003_accessrights_resourcepermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRightsPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.UUIDField(default=uuid.uuid4)),
                ('resource_id', models.UUIDField(default=uuid.uuid4)),
                ('accessright_id', models.UUIDField(default=uuid.uuid4)),
                ('ResourceName', models.CharField(max_length=255)),
                ('PermissionName', models.CharField(max_length=255)),
            ],
        ),
    ]
