# Generated by Django 4.0.3 on 2022-03-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0003_alter_role_lastmodifiedby_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestionmetadata',
            name='lastModifiedBy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tanksurveyquestionresponse',
            name='lastModifiedBy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastModifiedBy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='middleName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
