# Generated by Django 4.0.4 on 2022-07-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0004_accessrightspermissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbodysurveyresponse',
            name='name',
        ),
        migrations.AddField(
            model_name='waterbodyhydrologicresponse',
            name='tankName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
