# Generated by Django 4.0.4 on 2022-07-23 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0005_remove_waterbodysurveyresponse_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbodysurveyresponse',
            name='uniqueid',
        ),
        migrations.AddField(
            model_name='waterbodysurveyresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
