# Generated by Django 4.0.4 on 2022-07-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0007_waterbodysurveyresponse_uniqueid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbodysurveyresponse',
            name='legalissue',
        ),
        migrations.RemoveField(
            model_name='waterbodysurveyresponse',
            name='neerkattipractice',
        ),
    ]
