# Generated by Django 4.0.3 on 2022-05-07 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0009_block_monthfilling_panchayat_taluk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayat',
            name='blockId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.block'),
            preserve_default=False,
        ),
    ]
