# Generated by Django 4.0.4 on 2022-07-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0010_remove_waterbodyfreecatchmentresponse_sourcecontributiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbodyuppertanksluiceresponse',
            name='tankNumber',
        ),
    ]
