# Generated by Django 4.0.3 on 2022-05-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0010_panchayat_blockid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthFilling',
            new_name='Month',
        ),
    ]
