# Generated by Django 4.0.4 on 2022-07-25 00:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0011_remove_waterbodyuppertanksluiceresponse_tanknumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBodySurPlusSluiceFromUpperTankResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tankName', models.CharField(max_length=255)),
                ('contributiontypepercentage', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('seassonend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplusseassonend', to='waterBodyAdmin.month')),
                ('seassonstart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplusseassonstart', to='waterBodyAdmin.month')),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SurplusFromUpStream', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
        migrations.RemoveField(
            model_name='waterbodysurplusfromuppertankstreamissues',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='waterbodysurplusfromuppertankstreamissues',
            name='upperTankResponse',
        ),
        migrations.DeleteModel(
            name='WaterBodySurPlusFromUpperTankResponse',
        ),
        migrations.DeleteModel(
            name='WaterBodySurPlusFromUpperTankStreamIssues',
        ),
    ]
