# Generated by Django 4.0.4 on 2022-05-10 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0018_sectionquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionquestion',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.section'),
            preserve_default=False,
        ),
    ]
