# Generated by Django 4.0.4 on 2022-05-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0019_sectionquestion_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionquestion',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='sectionquestion',
            unique_together={('section', 'name')},
        ),
    ]
