# Generated by Django 4.0.4 on 2022-05-10 14:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0021_waterbodysectiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBodySurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('surveyno', models.CharField(max_length=255)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sectionquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='waterBodyAdmin.section'),
        ),
        migrations.CreateModel(
            name='WaterBodySourceResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('source1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodysource')),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodyHydrologicResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('waterspreadArea', models.IntegerField()),
                ('registeredAyacut', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('numberoffillings', models.IntegerField()),
                ('numberofsources', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('firstmonthfilling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstmonthfilling', to='waterBodyAdmin.month')),
                ('monthdryup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthdryup', to='waterBodyAdmin.month')),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodyFreeCatchmentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sourcecontributiontype', models.CharField(max_length=255)),
                ('contributiontypepercentage', models.IntegerField()),
                ('actualbreadth', models.IntegerField()),
                ('currentbreadth', models.IntegerField()),
                ('actualbottomwidth', models.IntegerField()),
                ('currentbottomwidth', models.IntegerField()),
                ('actualdepth', models.IntegerField()),
                ('currentdepth', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('seassonend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seassonend', to='waterBodyAdmin.month')),
                ('seassonstart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seassonstart', to='waterBodyAdmin.month')),
                ('streamtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodycrosssection')),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodyBasicDetailResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('village', models.CharField(max_length=255)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.block')),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodyownership')),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.panchayat')),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodysurveyresponse')),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.taluk')),
                ('waterbodytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodytype')),
            ],
        ),
    ]
