# Generated by Django 4.0.4 on 2022-05-10 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0022_waterbodysurveyresponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbodybasicdetailresponse',
            name='surveyResponse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='BasicDetail', to='waterBodyAdmin.waterbodysurveyresponse'),
        ),
    ]
