# Generated by Django 4.0.4 on 2022-05-11 07:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0023_alter_waterbodybasicdetailresponse_surveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBodySpreadResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('speciesName', models.CharField(max_length=255)),
                ('waterspreadareapercentage', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('surveyResponse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Spread', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
        migrations.AlterField(
            model_name='waterbodyfreecatchmentresponse',
            name='surveyResponse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='FreeCatchment', to='waterBodyAdmin.waterbodysurveyresponse'),
        ),
        migrations.AlterField(
            model_name='waterbodyhydrologicresponse',
            name='surveyResponse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='HydrologicParameter', to='waterBodyAdmin.waterbodysurveyresponse'),
        ),
        migrations.AlterField(
            model_name='waterbodysourceresponse',
            name='surveyResponse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SourceParameter', to='waterBodyAdmin.waterbodysurveyresponse'),
        ),
        migrations.CreateModel(
            name='WaterSpreadAreaIssueResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StreamIssues', to='waterBodyAdmin.waterbodystreamissues')),
                ('spreadResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpreadResponse', to='waterBodyAdmin.waterbodyspreadresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodySurPlusFromUpStreamResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tankName', models.CharField(max_length=255)),
                ('sourcecontributiontype', models.CharField(max_length=255)),
                ('contributiontypepercentage', models.IntegerField()),
                ('actualbreadth', models.IntegerField()),
                ('currentbreadth', models.IntegerField()),
                ('actualbottomwidth', models.IntegerField()),
                ('currentbottomwidth', models.IntegerField()),
                ('actualdepth', models.IntegerField()),
                ('currentdepth', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('seassonend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplusseassonend', to='waterBodyAdmin.month')),
                ('seassonstart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplusseassonstart', to='waterBodyAdmin.month')),
                ('streamtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodycrosssection')),
                ('surveyResponse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SurplusFromUpStream', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodySluiceUpStreamResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tankName', models.CharField(max_length=255)),
                ('tankSluiceNumber', models.IntegerField()),
                ('sourcecontributiontype', models.CharField(max_length=255)),
                ('contributiontypepercentage', models.IntegerField()),
                ('actualbreadth', models.IntegerField()),
                ('currentbreadth', models.IntegerField()),
                ('actualbottomwidth', models.IntegerField()),
                ('currentbottomwidth', models.IntegerField()),
                ('actualdepth', models.IntegerField()),
                ('currentdepth', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('seassonend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sluiceseassonend', to='waterBodyAdmin.month')),
                ('seassonstart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sluiceseassonstart', to='waterBodyAdmin.month')),
                ('streamtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodycrosssection')),
                ('surveyResponse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SluiceUpStream', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodyIrrigationCanalResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('canalName', models.CharField(max_length=255)),
                ('sourcecontributiontype', models.CharField(max_length=255)),
                ('bednature', models.CharField(max_length=255)),
                ('numberofSupplies', models.IntegerField()),
                ('contributiontypepercentage', models.IntegerField()),
                ('actualtopwidth', models.IntegerField()),
                ('currenttopwidth', models.IntegerField()),
                ('actualbottomwidth', models.IntegerField()),
                ('currentbottomwidth', models.IntegerField()),
                ('actualdepth', models.IntegerField()),
                ('currentdepth', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('firstseassonend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigationfirstseassonend', to='waterBodyAdmin.month')),
                ('firstseassonstart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigationfirstseassonstart', to='waterBodyAdmin.month')),
                ('secondseassonend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigationsecondseassonend', to='waterBodyAdmin.month')),
                ('secondseassonstart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigationsecondseassonstart', to='waterBodyAdmin.month')),
                ('streamtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodycrosssection')),
                ('surveyResponse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='IrigationCanal', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
    ]
