# Generated by Django 4.0.4 on 2022-05-11 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0024_waterbodyspreadresponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbodyspreadresponse',
            name='speciesName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExoticSpecies', to='waterBodyAdmin.waterbodyexoticspecies'),
        ),
    ]
