# Generated by Django 4.0.4 on 2022-05-11 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0025_alter_waterbodyspreadresponse_speciesname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterspreadareaissueresponse',
            name='spreadResponse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SpreadResponse', to='waterBodyAdmin.waterbodyspreadresponse'),
        ),
    ]
