# Generated by Django 4.0.4 on 2022-05-11 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0026_alter_waterspreadareaissueresponse_spreadresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterspreadareaissueresponse',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodystreamissues'),
        ),
        migrations.AlterField(
            model_name='waterspreadareaissueresponse',
            name='spreadResponse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SpreadAreaIssues', to='waterBodyAdmin.waterbodyspreadresponse'),
        ),
    ]
