# Generated by Django 4.0.4 on 2022-05-11 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0027_alter_waterspreadareaissueresponse_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterspreadareaissueresponse',
            name='spreadResponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpreadAreaIssues', to='waterBodyAdmin.waterbodyspreadresponse'),
        ),
    ]
