# Generated by Django 4.0.4 on 2022-05-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0031_alter_waterspreadareaissueresponse_issue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterspreadareaissueresponse',
            name='issue',
        ),
    ]
