# Generated by Django 4.0.4 on 2022-05-11 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0032_remove_waterspreadareaissueresponse_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterspreadareaissueresponse',
            name='spreadResponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='waterBodyAdmin.waterbodyspreadresponse'),
        ),
    ]
