# Generated by Django 4.0.4 on 2022-05-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0033_alter_waterspreadareaissueresponse_spreadresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbodyspreadresponse',
            name='issues',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WaterSpreadAreaIssueResponse',
        ),
    ]
