# Generated by Django 4.0.4 on 2022-05-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0034_waterbodyspreadresponse_issues_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbodysurveyresponse',
            name='surveyno',
        ),
        migrations.AddField(
            model_name='waterbodybasicdetailresponse',
            name='surveyno',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterbodysurveyresponse',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
