# Generated by Django 4.0.4 on 2022-05-11 12:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0035_remove_waterbodysurveyresponse_surveyno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBodyBundResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bundlength', models.IntegerField()),
                ('bundtopwidth', models.IntegerField()),
                ('slopeforeside', models.IntegerField()),
                ('sloperearside', models.IntegerField()),
                ('bundreventment', models.CharField(max_length=10)),
                ('bundreventmentinterval', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('stonepitchingcondition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stonepitchingconditions', to='waterBodyAdmin.waterbodystonepitchingcondition')),
                ('surveyResponse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Bund', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
    ]
