# Generated by Django 4.0.4 on 2022-05-12 00:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0038_waterbodyspreadissues'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBodyBundStonePitchings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('bundResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pitchings', to='waterBodyAdmin.waterbodybundresponse')),
                ('stonePitching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodystonepitching')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodyBundIssues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('bundResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Issues', to='waterBodyAdmin.waterbodybundresponse')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodystreamissues')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodyBundFunctionalites',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('bundResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Functionalites', to='waterBodyAdmin.waterbodybundresponse')),
                ('bundfunctionality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodybund')),
            ],
        ),
    ]
