# Generated by Django 4.0.4 on 2022-05-12 03:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0039_waterbodybundstonepitchings_waterbodybundissues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBodySurplusweirResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('surplusweirnumber', models.IntegerField()),
                ('surplusweirLength', models.IntegerField()),
                ('mwlstonedepth', models.IntegerField()),
                ('leveldifference', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('mwlstones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MWLStone', to='waterBodyAdmin.waterbodymwlstone')),
                ('shutterType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SurplusweirShutterType', to='waterBodyAdmin.waterbodyshutter')),
                ('silllevelDepth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SurplusweirSillLevelDepth', to='waterBodyAdmin.waterbodydepthsilllevel')),
                ('surplusweircondition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Surplusweircondition', to='waterBodyAdmin.waterbodysluicecondition')),
                ('surplusweirtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Surplusweirtype', to='waterBodyAdmin.waterbodysurplusweir')),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Surplusweir', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodySurpluCoarseResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tankName', models.CharField(max_length=255)),
                ('actualbreadth', models.IntegerField()),
                ('currentbreadth', models.IntegerField()),
                ('actualbottomwidth', models.IntegerField()),
                ('currentbottomwidth', models.IntegerField()),
                ('actualdepth', models.IntegerField()),
                ('currentdepth', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('streamtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodycrosssection')),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SurpluCoarse', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodySurpluCoarseIssues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodystreamissues')),
                ('surpluCoarseResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Issues', to='waterBodyAdmin.waterbodysurplucoarseresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodySluiceResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sluicenumber', models.IntegerField()),
                ('sluiceIrrigatedArea', models.IntegerField()),
                ('sluicefeedanywaterbody', models.CharField(max_length=10)),
                ('waterbodyname', models.CharField(max_length=255)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('shutterType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SluiceShutterType', to='waterBodyAdmin.waterbodyshutter')),
                ('shuttercondition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShutterCondition', to='waterBodyAdmin.waterbodysluicecondition')),
                ('silllevelDepth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SluiceSillLevelDepth', to='waterBodyAdmin.waterbodydepthsilllevel')),
                ('sluicecondition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SluiceCondition', to='waterBodyAdmin.waterbodysluicecondition')),
                ('sluicetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SluiceType', to='waterBodyAdmin.waterbodysluice')),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sluice', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
    ]
