# Generated by Django 4.0.4 on 2022-05-12 04:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0040_waterbodysurplusweirresponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBodyTankBedCultivationResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('area', models.IntegerField()),
                ('dependentfamiliesnumber', models.IntegerField()),
                ('investment', models.IntegerField()),
                ('returns', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('monthofharvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TankBedMonthofharvest', to='waterBodyAdmin.month')),
                ('monthofrelease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TankBedMonthofrelease', to='waterBodyAdmin.month')),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TankBedCultivation', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodyTankBedFamilies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodyfamilynature')),
                ('tankBedResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Families', to='waterBodyAdmin.waterbodytankbedcultivationresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodyTankBedDistributionLands',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('distributionLand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodyfamilydistributionland')),
                ('tankBedResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DistributionLands', to='waterBodyAdmin.waterbodytankbedcultivationresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodyLotusCultivationResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('investment', models.IntegerField()),
                ('returns', models.IntegerField()),
                ('dependentfamiliesnumber', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('investmentnature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LotusInvestmentnature', to='waterBodyAdmin.waterbodyinvestmentnature')),
                ('monthofharvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LotusMonthofharvest', to='waterBodyAdmin.month')),
                ('monthofrelease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LotusMonthofrelease', to='waterBodyAdmin.month')),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LotusCultivation', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodyIrrigationResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ayacutcultivation', models.IntegerField()),
                ('firstcropname', models.CharField(max_length=255)),
                ('secondcropname', models.CharField(max_length=255)),
                ('thirdcropname', models.CharField(max_length=255)),
                ('dugwellnumber', models.IntegerField()),
                ('depthofdugwell', models.IntegerField()),
                ('borewellnumber', models.IntegerField()),
                ('maxborewelldepth', models.IntegerField()),
                ('dependentfamiliesnumber', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('ayacutnature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodyayacutnoncultivation')),
                ('cropping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodycropping')),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Irrigation', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodyFishingResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('investment', models.IntegerField()),
                ('returns', models.IntegerField()),
                ('dependentfamiliesnumber', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('investmentnature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Investmentnature', to='waterBodyAdmin.waterbodyinvestmentnature')),
                ('monthofharvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Monthofharvest', to='waterBodyAdmin.month')),
                ('monthofrelease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Monthofrelease', to='waterBodyAdmin.month')),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fishing', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
    ]
