# Generated by Django 4.0.4 on 2022-05-12 04:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0041_waterbodytankbedcultivationresponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBodyTankUniquenessResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodytankuniqueness')),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TankUniqueness', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodyHarvestFromBundTreeResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('investment', models.IntegerField()),
                ('returns', models.IntegerField()),
                ('dependentfamiliesnumber', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('investmentnature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BundTreeInvestmentnature', to='waterBodyAdmin.waterbodyinvestmentnature')),
                ('monthofharvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HarvestFromBundMonthofharvest', to='waterBodyAdmin.month')),
                ('monthofrelease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HarvestFromBundMonthofrelease', to='waterBodyAdmin.month')),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HarvestFromBundTree', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodyForPotteryResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dependentfamiliesnumber', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pottery', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodyForLiveStockResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dependentfamiliesnumber', models.IntegerField()),
                ('dependentanimalssnumber', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LiveStock', to='waterBodyAdmin.waterbodysurveyresponse')),
            ],
        ),
    ]
