# Generated by Django 4.0.4 on 2022-05-12 07:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0042_waterbodytankuniquenessresponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBodyFunctionalParameterResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedBy', models.CharField(blank=True, max_length=255)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('surveyResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FunctionalParameters', to='waterBodyAdmin.waterbodysurveyresponse')),
                ('tankFunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterBodyAdmin.waterbodyirrigationtankfunction')),
            ],
        ),
    ]
