# Generated by Django 4.0.4 on 2022-05-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0043_waterbodyfunctionalparameterresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbodysurveyresponse',
            name='legalissue',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterbodysurveyresponse',
            name='neerkattipractice',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterbodysurveyresponse',
            name='status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
