# Generated by Django 4.0.4 on 2022-05-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterBodyAdmin', '0046_waterbodydrinkingresponse_waterbodydomesticresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbodyspreadresponse',
            name='issues',
        ),
    ]
